name: tencent_docker
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

env:
  TENCENT_NAME_SPACE: "${{ secrets.TENCENT_NAME_SPACE }}"
  TENCENT_REGISTRY_USER: "${{ secrets.TENCENT_REGISTRY_USER }}"
  TENCENT_REGISTRY_PASSWORD: "${{ secrets.TENCENT_REGISTRY_PASSWORD }}"
  ERROR_LOG_FILE: error.log

jobs:
  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and push image TENCENT
        run: |
          docker login https://ccr.ccs.tencentyun.com -u $TENCENT_REGISTRY_USER -p $TENCENT_REGISTRY_PASSWORD
          while IFS= read -r line; do
            [[ -z "$line" ]] && continue
            echo "docker pull $line"
            docker pull "$line" || { echo "Failed to pull $line" >> $ERROR_LOG_FILE; }
            image=$(echo "$line" | awk '{print $NF}')
            image_name_tag=$(echo "$image" | awk -F'/' '{print $NF}')
            new_image="ccr.ccs.tencentyun.com/$TENCENT_NAME_SPACE/$image_name_tag"
            echo "docker tag $image $new_image"
            docker tag "$image" "$new_image"
            echo "docker push $new_image"
            docker push "$new_image"
          done < images.txt